/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.usuarios;

import controlador.ControladorUsuario;
/**
 *
 * @author Patin
 */
public class VistaUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaUsuario.class.getName());

    /**
     * Creates new form VistaUsuario
     */
    private ControladorUsuario controlador;
    
    public VistaUsuario(ControladorUsuario controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
        inicializarPaneles(controlador); // 👈 Esto carga los paneles en el CardLayout
        mostrarPanel("menu"); 
    }
    
        // Método para inicializar los paneles del CRUD
    public void inicializarPaneles(ControladorUsuario controlador) {
        panelPrincipal.setLayout(new java.awt.CardLayout());

        // Agregar los paneles (usa los nombres de tus clases reales)
        panelPrincipal.add(new vista.usuarios.panelMenuUsuario(this,controlador), "menu");
        panelPrincipal.add(new vista.usuarios.panelAgregarUsuario(this,controlador), "agregar");
        // Luego podrás agregar los demás (editar, borrar, etc.)
    }

    // Método para mostrar un panel por nombre
    public void mostrarPanel(String nombre) {
        java.awt.CardLayout cl = (java.awt.CardLayout) panelPrincipal.getLayout();
        cl.show(panelPrincipal, nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        mnuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mitAgregar = new javax.swing.JMenuItem();
        mitListar = new javax.swing.JMenuItem();
        mitBuscar = new javax.swing.JMenuItem();
        mitBorrar = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mitSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mitAgregar.setText("Agregar");
        mitAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAgregarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mitAgregar);

        mitListar.setText("Listar");
        mnuArchivo.add(mitListar);

        mitBuscar.setText("Buscar");
        mnuArchivo.add(mitBuscar);

        mitBorrar.setText("Borrar");
        mnuArchivo.add(mitBorrar);

        mnuBar.add(mnuArchivo);

        mnuOpciones.setText("Opciones");

        mitSalir.setText("Salir");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        mnuOpciones.add(mitSalir);

        mnuBar.add(mnuOpciones);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAgregarActionPerformed
        mostrarPanel("agregar");
        // TODO add your handling code here:
    }//GEN-LAST:event_mitAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaUsuario(new controlador.ControladorUsuario()).setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mitAgregar;
    private javax.swing.JMenuItem mitBorrar;
    private javax.swing.JMenuItem mitBuscar;
    private javax.swing.JMenuItem mitListar;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JPanel getPanelPrincipal() {
        return panelPrincipal;
    }
}
